- name: Export Host Metrics to CSV
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Get Host Metrics from API
      ansible.builtin.uri:
        url: "https://aap.home.lab/api/controller/v2/host_metrics/"
        method: GET
        user: "{{ lookup('env', 'CONTROLLER_USERNAME') }}"
        password: "{{ lookup('env', 'CONTROLLER_PASSWORD') }}"
       # user: "admin"
       # password: "Hajia786!"
        force_basic_auth: yes
        validate_certs: no
      register: response

   # - name: Look at raw data for one host
   #   ansible.builtin.debug:
   #     msg: "{{ response.json.results[0] }}"
   #   when: response.json.results | length > 0
      
    - name: Write metrics to CSV file
      ansible.builtin.copy:
        content: |
          Hostname, Last Automated, Status
          {% for host in response.json.results %}
          {{ host.hostname | default('N/A') }}, {{ host.last_automation | default('N/A') }}, {{ host.automated_counter | default('N/A') }}
          {% endfor %}
        dest: "./host_metrics_report.csv"
      when: response.json.results is defined
      
    - name: Ship CSV to a permanent server
      ansible.builtin.copy:
        src: "./host_metrics_report.csv"
        dest: "/tmp/host_metrics_{{ ansible_date_time.date }}.csv"
      delegate_to: aap.home.lab